import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import { ParticipantReportRow } from "@/types/report";

export interface PdfReportOptions {
  quizTitle: string;
  gamePin: string;
  hostName: string;
  dateStr?: string;
  totalParticipants: number;
  totalQuestions: number;
  highestScore: number;
  averageScore: number;
  averageAccuracy: number;
  participants: ParticipantReportRow[];
}

export function generatePdfReport(options: PdfReportOptions) {
  const doc = new jsPDF({
    orientation: "portrait",
    unit: "mm",
    format: "a4",
  });

  const primaryColor = [79, 70, 229]; // Indigo brand
  const darkTextColor = [30, 41, 59];
  const mutedTextColor = [100, 116, 139];

  // 1. Header Banner
  doc.setFillColor(15, 23, 42); // slate-900
  doc.rect(0, 0, 210, 38, "F");

  // App Logo & Title
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(22);
  doc.setFont("helvetica", "bold");
  doc.text("DQUIZ", 14, 18);

  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(199, 210, 254);
  doc.text("Official Quiz Performance & Results Report", 14, 26);

  // Date and PIN on Right
  doc.setFontSize(9);
  doc.setTextColor(226, 232, 240);
  doc.text(`Game PIN: ${options.gamePin}`, 196, 16, { align: "right" });
  doc.text(`Date: ${options.dateStr || new Date().toLocaleDateString()}`, 196, 22, { align: "right" });
  doc.text(`Host: ${options.hostName}`, 196, 28, { align: "right" });

  // 2. Quiz Title
  doc.setTextColor(darkTextColor[0], darkTextColor[1], darkTextColor[2]);
  doc.setFontSize(16);
  doc.setFont("helvetica", "bold");
  doc.text(options.quizTitle, 14, 48);

  // 3. KPI Summary Cards
  const startY = 54;
  const boxWidth = 34;
  const boxHeight = 18;
  const gap = 4;

  const kpis = [
    { label: "Participants", val: String(options.totalParticipants) },
    { label: "Questions", val: String(options.totalQuestions) },
    { label: "Top Score", val: String(options.highestScore) },
    { label: "Avg Score", val: String(options.averageScore) },
    { label: "Avg Accuracy", val: `${options.averageAccuracy}%` },
  ];

  kpis.forEach((kpi, idx) => {
    const x = 14 + idx * (boxWidth + gap);
    doc.setFillColor(241, 245, 249); // slate-100
    doc.roundedRect(x, startY, boxWidth, boxHeight, 2, 2, "F");

    doc.setFontSize(7.5);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(mutedTextColor[0], mutedTextColor[1], mutedTextColor[2]);
    doc.text(kpi.label.toUpperCase(), x + boxWidth / 2, startY + 6, { align: "center" });

    doc.setFontSize(12);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(15, 23, 42);
    doc.text(kpi.val, x + boxWidth / 2, startY + 14, { align: "center" });
  });

  // 4. Participant Results Table
  const tableData = options.participants.map((p) => [
    `#${p.rank}`,
    p.name,
    p.rollNumber,
    p.score.toLocaleString(),
    String(p.correct),
    String(p.incorrect),
    p.accuracy,
  ]);

  autoTable(doc, {
    startY: 78,
    head: [["Rank", "Student Name", "Roll Number", "Score", "Correct", "Incorrect", "Accuracy"]],
    body: tableData,
    theme: "striped",
    headStyles: {
      fillColor: [79, 70, 229],
      textColor: [255, 255, 255],
      fontStyle: "bold",
      fontSize: 9,
    },
    styles: {
      fontSize: 8.5,
      cellPadding: 3,
      textColor: [30, 41, 59],
    },
    columnStyles: {
      0: { cellWidth: 15, halign: "center", fontStyle: "bold" },
      1: { fontStyle: "bold" },
      2: { cellWidth: 30, fontStyle: "normal" },
      3: { cellWidth: 22, halign: "right", fontStyle: "bold" },
      4: { cellWidth: 18, halign: "center" },
      5: { cellWidth: 18, halign: "center" },
      6: { cellWidth: 22, halign: "center", fontStyle: "bold" },
    },
    didDrawPage: (data) => {
      // 5. Footer on every page
      const pageHeight = doc.internal.pageSize.height || 297;
      doc.setFontSize(8);
      doc.setFont("helvetica", "normal");
      doc.setTextColor(148, 163, 184);
      doc.text(
        "Generated by DQUIZ Standalone Real-Time Quiz Platform",
        14,
        pageHeight - 10
      );
      doc.text(
        `Page ${data.pageNumber}`,
        196,
        pageHeight - 10,
        { align: "right" }
      );
    },
  });

  const sanitizedName = options.quizTitle.replace(/[^a-zA-Z0-9_-]/g, "_");
  const dateStr = new Date().toISOString().split("T")[0];
  doc.save(`${sanitizedName}_Final_Results_${dateStr}.pdf`);
}
